language: python
cache: pip
dist: xenial

matrix:
  include:
  - python: 3.5
    #before_install: ""
    before_script: ""
  - python: 3.6
  - python: 3.7
  - python: 3.8
    dist: bionic
  - python: 3.9
    dist: bionic

before_install:
  - "make reqs-install"

install:
  - "pip install ."

before_script:
  # stop here if linting fails
  - "make lint"
  - "make mypy"

script:
  - make samples-download
  # could be much improved ...
  - "find exif-samples-master -name *.tiff -o -name *.jpg | sort -f | xargs EXIF.py > exif-samples-master/dump_test"
  - "diff -y --suppress-common-lines exif-samples-master/dump exif-samples-master/dump_test"
  # test colors
  - "find exif-samples-master -name *.tiff -o -name *.jpg | xargs EXIF.py -dc"
